## Use this workflow manually to create a hotfix PR from specific commits of the development branch to the release-candidate branch.
name: Create hotfix request ðŸž

on:
  workflow_dispatch:
    inputs:
      commit_hashes:
        description: 'Put here the commit hashes from development branch to include in the hotfix, separated by commas'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  hotfix:
    name: Create hotfix PR from commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create hotfix branch from release-candidate
        run: |
          git checkout release-candidate
          git pull origin release-candidate
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git checkout -b hotfix/$VERSION
      
      - name: Cherry-pick commits
        run: |
          IFS=',' read -ra COMMITS <<< "${{ github.event.inputs.commit_hashes }}"
          for commit in "${COMMITS[@]}"; do
            git cherry-pick "$commit"
          done
      
      - name: bump version for hotfix
        run: |
          cd scripts
          ./bump_version.sh
          ./bump_flutter_version.sh

          cd ..

          git add version.txt pubspec.yaml
          git commit -m "Release: Bump version to $(cat version.txt)"
      
      - name: Push hotfix branch
        run: |
          git push origin hotfix/$VERSION

      - name: Create pull request
        run: |
          gh pr create --title "Release: Hotfix on $VERSION" --body $'Hotfix PR with the following commits: \n\n'"${{ github.event.inputs.commit_hashes }}" --head hotfix/$VERSION --base release-candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}